### PR TITLE
fix typo branch merging conflict

### PR DESCRIPTION
**Pull request by fakela**

### CODE REVIEW

**Comment by fharper** [comment]
You didn't update your branch with my modification... I'll redo the commit.

**Comment by fharper** [comment]
Also, since it's coming from your fork, I cannot push directly to it. Not sure why it's a new PR, and not just commits on the previous one.

Can you change librairies also in the config.yml file please

**Review by fharper — CHANGES_REQUESTED** [review]
As mentioned in my previous comment: the config file for sync is missing the change of name

**Comment by fakela** [comment]
Okay

**Comment by fakela** [comment]
> Also, since it's coming from your fork, I cannot push directly to it. Not sure why it's a new PR, and not just commits on the previous one.
> 
> Can you change librairies also in the config.yml file please

 When I followed the command line for resolving merge conflict, it came as a new PR

**Pull request merged**
