### PR TITLE
update train your endpoint via API page by @olivmindee

### PR DESCRIPTION
**Pull request by fharper**
TODO: fix the two links @olivmindee wants, but not sure where to link

NOTE: if it's merge before my working hours, the deleted page needs to be manually deleted from the README.io interface since the sync doesn't delete pages

### CODE REVIEW

**Comment by fharper** [comment]
Doesn't make sense to review the changes since I delete all the content and replaced it by yours. You can view the file as in the commit on GitHub when you review. To make it easier, here the direct link https://github.com/mindee/documentation/blob/e3a974e06ea35379d43886346f6e1a6f512d7801/build-your-first-document-parsing-api/training-interface/train-using-the-annotation-endpoint.md

**Comment by fharper** [comment]
@fakela we won't update the code examples to be complete (proper `cURL` call, real examples with a document, complete `JSON` output...) nor the text like in the rest of the documentation. @olivmindee said it was ok like that.

**Comment by fakela** [comment]
> @fakela we won't update the code examples to be complete (proper `cURL` call, real examples with a document, complete `JSON` output...) nor the text like in the rest of the documentation. @olivmindee said it was ok like that.

#330

**Comment by fharper** [comment]
Not sure why the "README.io syntax" validation failed as the links are working, I tested them again. Should not caused problem for syncing, and I guess they will be recognized by the syntax validator once live.

**Comment by fakela** [comment]
> Not sure why the "README.io syntax" validation failed as the links are working, I tested them again. Should not caused problem for syncing, and I guess they will be recognized by the syntax validator once live.

Can i make edits to this or i shouldn’t

**Comment by fharper** [comment]
> > Not sure why the "README.io syntax" validation failed as the links are working, I tested them again. Should not caused problem for syncing, and I guess they will be recognized by the syntax validator once live.
> 
> Can i make edits to this or i shouldn’t

As mentioned, no https://github.com/mindee/documentation/pull/386#issuecomment-1069756600

**Comment by fakela** [comment]
Upload document via API

> > > Not sure why the "README.io syntax" validation failed as the links are working, I tested them again. Should not caused problem for syncing, and I guess they will be recognized by the syntax validator once live.
> > 
> > 
> > Can i make edits to this or i shouldn’t
> 
> As mentioned, no [#386 (comment)](https://github.com/mindee/documentation/pull/386#issuecomment-1069756600)

yeah it's more o structure and presenting the information better

**Comment by fharper** [comment]
Check with @olivmindee if he is OK with that please.

**Comment by fakela** [comment]
> Check with @olivmindee if he is OK with that please.

I will check with him tommorow

**Comment by fakela** [comment]
The title is a bit of a no for me, we can do this
Use Mindee API to train your endpoint -> Train your endpoint with Mindee API

**Pull request merged**
