### PR TITLE
fix folder name typo

### PR DESCRIPTION
**Pull request by fakela**
@fharper this is a PR for the folder name typo, if you are still available it will be nice to review this and merge

### CODE REVIEW

**Review by fharper — APPROVED** [review]
LGTM

**Comment by fharper** [comment]
@fakela can you fix the merge conflicts please

**Comment by fakela** [comment]
> @fakela can you fix the merge conflicts please

Okay

**Comment by fharper** [comment]
Deleting since you create another branch with the same commits + the merge fixed.

**Pull request closed without merging**
